FROM golang AS builder
workdir /go
COPY server.go .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server server.go

FROM debian:bullseye-slim as prod
workdir /go
COPY --from=builder /go/server .
CMD ["./server"]